repo:
  path: repo
  url: https://github.com/neovim/neovim

date_range:
  start: "all"
  end: ""

sources:
  git: true
  github_actions: false
  jira:
    enabled: false
    projects: []
    base_url: ""

rendering:
  style: network
  output: neovim.mp4
  fps: 30
  resolution: [1920, 1080]
  video_speed:
    mode: duration
    value: 60
